name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.3.0"
          cache: "npm"
      - run: npm install
      - name: Check Format
        run: npm run format:check
      - name: Lint
        run: npm run lint:check
      - name: Run Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    # We only want to deploy from trunk, never for pull requests!
    if: ${{ ! startsWith(github.event_name, 'pull_request') }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.3.0"
          cache: "npm"
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
