name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.3.0"
          cache: "npm"
      - run: npm install
      - name: Check Format
        run: npm run format:check
      - name: Lint
        run: npm run lint:check
      - name: Run Tests
        run: npm test
      - name: Run E2E Tests
        run: npm test:e2e

  deploy:
    runs-on: ubuntu-latest
    # We only want to deploy from trunk, never for pull requests!
    if: ${{ ! startsWith(github.event_name, 'pull_request') }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.3.0"
          cache: "npm"
      - run: npm install
      - run: npm run build
      - name: Deploy
        # Third-party action, pin to commit SHA!
        # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # == v3.8.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
